import java.io.*;
public class FileApp
{
	public static void main(String x[])
	{/*
	File f[]=File.listRoots();
	for(int i=0; i<f.length;i++) {
			long totalSpace=f[i].getTotalSpace();
			long FreeSpace=f[i].getFreeSpace();
			long usedSpace=totalSpace-FreeSpace;
            System.out.println(f[i]+"\t Total Space: - "+(totalSpace/1073741824)+"\t Free Space: - "+(FreeSpace/1073741824)+"\t  Used Space: - "+(usedSpace/1073741824));
		}
		File fi=new File("G:\\java Practical\\Abhi\\Demo");
		boolean b1=fi.exists();
		if(b1)
		{
			System.out.println("This path for file is already exists");
		}
		else 
		{
			System.out.println("This path is not file is already exists");
		}
	
		File f=new File("G:\\java Practical\\Abhi\\Demo");
		boolean b=f.isFile();
		if(b)
		{
			System.out.println("Path content is file");	
		}
		else
		{
			System.out.println("Path is not file");
		}
			
		File f=new File("G:\\java Practical\\Abhi\\Demo");
		boolean b=f.isDirectory();
		if(b)
		{
			System.out.println("Path is directory");
		}
		else
		{
			System.out.println("path is not directory");
		}*/

	}
}